# Generated by Django 2.0.2 on 2018-10-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
                ('salary', models.IntegerField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.SmallIntegerField(null=True)),
                ('birth', models.DateField(null=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
