# Generated by Django 2.0.2 on 2018-10-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('pic', models.ImageField(upload_to='user_pic')),
            ],
            options={
                'db_table': 't_user',
            },
        ),
    ]
