# Generated by Django 2.0.2 on 2018-10-31 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc_app', '0001_initial'),
        ('task_app', '0003_auto_20181030_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doc_app.dept'),
        ),
        migrations.AlterField(
            model_name='task',
            name='pic1',
            field=models.ImageField(default='user/wupingguo.jpg', null=True, upload_to='user'),
        ),
    ]
