# Generated by Django 2.0.2 on 2018-10-28 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zuoye_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='rele',
            field=models.ForeignKey(db_column='cate_id', on_delete=django.db.models.deletion.CASCADE, to='zuoye_app.Category'),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='t_employee',
        ),
    ]
