# Generated by Django 2.0.2 on 2018-10-28 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zuoye_app', '0003_auto_20181028_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctitle', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 't_category',
            },
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('birth', models.DateTimeField()),
                ('rele', models.ForeignKey(db_column='cate_id', on_delete=django.db.models.deletion.CASCADE, to='zuoye_app.Category')),
            ],
            options={
                'db_table': 't_employee',
            },
        ),
    ]
