# Generated by Django 2.0.2 on 2018-10-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zuoye_app', '0004_category_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursr_name', models.CharField(max_length=10)),
                ('creat_time', models.DateTimeField(auto_now=True)),
                ('rel', models.ManyToManyField(to='zuoye_app.Student')),
            ],
            options={
                'db_table': 't_course',
            },
        ),
    ]
