# Generated by Django 2.0.2 on 2018-10-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='Operation',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
