# Generated by Django 2.0.2 on 2018-10-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, null=True)),
                ('name', models.CharField(max_length=10, null=True)),
                ('password', models.CharField(max_length=10, null=True)),
                ('sex', models.SmallIntegerField(null=True)),
                ('birth', models.DateField(null=True)),
            ],
            options={
                'db_table': 'admin_t',
            },
        ),
    ]
